# Création de Dataset

In [1]:
def preprocess_df(df):
    dataframe = df.copy()
    dataframe[['patient_id', 'date']] = dataframe['recording_id'].str.split('/', expand=True)

    #mettre patient et date en premier
    cols = dataframe.columns.tolist()
    cols = ['patient_id', 'date'] + [col for col in cols if col not in ['patient_id', 'date']]
    dataframe = dataframe[cols]

    dataframe = dataframe.drop(columns=['recording_id'])

    #enlever 'patient_' et tous les 0 avant de la colonne patient_id sauf si c'est le seul caractère
    dataframe['patient_id'] = dataframe['patient_id'].str.replace('patient_', '', regex=False).str.lstrip('0')
    dataframe['patient_id'] = dataframe['patient_id'].replace('', '0')

    return dataframe

def str_dict_to_dict(s):
    import ast
    try:
        return ast.literal_eval(s)
    
    except (ValueError, SyntaxError):
        return {}  # Return an empty dictionary if conversion fails

In [4]:
import pandas as pd 

data = pd.read_parquet("data/dataset.parquet")

data = preprocess_df(data)

data.head()

,patient_id,date,start_time,end_time,audspec_lengthL1norm_sma_iqr1_2,audspec_lengthL1norm_sma_iqr2_3,audspec_lengthL1norm_sma_iqr1_3,audspec_lengthL1norm_sma_percentile50_0,audspec_lengthL1norm_sma_stddev,audspec_lengthL1norm_sma_amean,...,logHNR_sma_de_iqr2_3,logHNR_sma_de_iqr1_3,logHNR_sma_de_percentile50_0,logHNR_sma_de_stddev,F0final_sma_ff0_nnz,patient_short_id,label,age,sex,audio_quality
13946,0,2021-09-17,576,776,1.493601,0.472047,1.965648,2.107094,1.026020,1.629121,...,2.196668,2.462965,0.370440,2.792117,0.923077,patient_0000,0,0.738636,1,0.761684
14070,0,2021-09-17,3008,3208,0.276523,0.181809,0.458331,0.774141,0.294968,0.704204,...,0.160649,0.178956,0.016412,0.104311,1.000000,patient_0000,0,0.738636,1,0.913146
14071,0,2021-09-17,3076,3276,0.232940,0.161391,0.394331,0.761261,0.268565,0.692789,...,0.204947,0.269043,0.074313,0.140533,1.000000,patient_0000,0,0.738636,1,0.921234
14072,0,2021-09-17,3076,3276,0.211107,0.261235,0.472341,0.866216,0.319627,0.833112,...,0.196939,0.277636,0.082456,0.143403,1.000000,patient_0000,0,0.738636,1,0.921234
14073,0,2021-09-17,3076,3276,0.246978,0.158901,0.405880,0.779031,0.273051,0.702328,...,0.206352,0.269329,0.072969,0.140931,1.000000,patient_0000,0,0.738636,1,0.921234

In [5]:
test = data[(data['date'] == '2021-09-17') & (data['patient_id'] == '0')]

start_times = {}

for index, row in test.iterrows():
    if str(row['start_time']) in start_times:
        start_times[str(row['start_time'])] += 1
    else:
        start_times[str(row['start_time'])] = 1

#trier start_times par valeur croissante
start_times = dict(sorted(start_times.items(), key=lambda item: item[1], reverse=True))

start_times

{'576': 4,
 '3076': 4,
 '3176': 4,
 '2976': 4,
 '3276': 4,
 '3376': 4,
 '2576': 4,
 '2676': 4,
 '2776': 4,
 '2876': 4,
 '3476': 4,
 '3976': 4,
 '4075': 4,
 '4176': 4,
 '4276': 4,
 '3576': 4,
 '3676': 4,
 '3776': 4,
 '3876': 4,
 '2476': 4,
 '1076': 4,
 '1176': 4,
 '1276': 4,
 '1376': 4,
 '1476': 4,
 '976': 4,
 '676': 4,
 '776': 4,
 '876': 4,
 '1576': 4,
 '2076': 4,
 '2176': 4,
 '2276': 4,
 '2376': 4,
 '1976': 4,
 '1676': 4,
 '1776': 4,
 '1876': 4,
 '4376': 2,
 '3008': 1,
 '3108': 1,
 '3308': 1,
 '3208': 1,
 '3408': 1,
 '2608': 1,
 '2708': 1,
 '2808': 1,
 '2908': 1,
 '4008': 1,
 '4108': 1,
 '4208': 1,
 '4308': 1,
 '4408': 1,
 '3908': 1,
 '3508': 1,
 '3608': 1,
 '3708': 1,
 '3808': 1,
 '2508': 1,
 '1108': 1,
 '1208': 1,
 '1308': 1,
 '1408': 1,
 '1008': 1,
 '608': 1,
 '708': 1,
 '808': 1,
 '908': 1,
 '2108': 1,
 '2208': 1,
 '2308': 1,
 '2408': 1,
 '1508': 1,
 '2008': 1,
 '1608': 1,
 '1708': 1,
 '1808': 1,
 '1908': 1}

In [8]:
data_augmented = pd.read_parquet('Hackathon/dataset_with_aug_dict.parquet')

data_augmented = preprocess_df(data_augmented)

data_augmented.head()

,patient_id,date,start_time,end_time,augmentation_dict,audspec_lengthL1norm_sma_iqr1_2,audspec_lengthL1norm_sma_iqr2_3,audspec_lengthL1norm_sma_iqr1_3,audspec_lengthL1norm_sma_percentile50_0,audspec_lengthL1norm_sma_stddev,...,logHNR_sma_de_iqr2_3,logHNR_sma_de_iqr1_3,logHNR_sma_de_percentile50_0,logHNR_sma_de_stddev,F0final_sma_ff0_nnz,patient_short_id,label,age,sex,audio_quality
0,2,2021-10-01,480,680,"{""augmentation"": ""original""}",0.824093,0.237206,1.061300,1.294769,0.601383,...,0.178952,0.204519,0.065431,0.157982,1.000000,patient_0002,0,0.909091,0,0.557534
1,2,2021-10-01,480,680,"{""pitch_shift"": null, ""time_stretch"": null, ""r...",0.825607,0.208997,1.034604,1.211626,0.564895,...,0.133620,0.190211,0.089150,0.180251,1.000000,patient_0002,0,0.909091,0,0.557534
2,2,2021-10-01,480,680,"{""pitch_shift"": 0.31846850944034655, ""time_str...",0.655419,0.376667,1.032087,1.198619,0.577098,...,5.281692,5.338002,0.086555,3.712759,0.846154,patient_0002,0,0.909091,0,0.557534
3,2,2021-10-01,480,680,"{""pitch_shift"": null, ""time_stretch"": null, ""r...",0.679861,0.330526,1.010386,1.171579,0.563352,...,0.221065,0.251099,0.082160,0.181627,1.000000,patient_0002,0,0.909091,0,0.557534
4,2,2021-10-01,576,776,"{""pitch_shift"": null, ""time_stretch"": 0.835476...",0.635661,0.266532,0.902193,1.221095,0.526917,...,5.344244,5.419852,0.062196,3.722184,0.846154,patient_0002,0,0.909091,0,0.809958

In [9]:
test = data_augmented.copy()

#ajouter une colonne recording_id qui est vide pour l'instant
test['recording_id'] = ''

test_df = {
    c : [] for c in test.columns if c != 'augmentation_dict'
}


for patient in test['patient_id'].unique():
    print(f"Processing patient {patient}")
    patient_data = test[test['patient_id'] == patient]
    for date in patient_data['date'].unique():
        date_data = patient_data[patient_data['date'] == date]
        
        augmentations = date_data['augmentation_dict'].unique().tolist()

        aug_dic = {
            augmentations[i] : i for i in range(len(augmentations))
        }

        for i,row in date_data.iterrows():
            aug_index = aug_dic[row['augmentation_dict']]
            recording_id = aug_index
            
            for c in test_df.keys():
                if c == 'recording_id':
                    test_df[c].append(recording_id)
                else:
                    test_df[c].append(row[c])

test_df = pd.DataFrame(test_df)

#mette en premier patient_id, recording_id, date, start_time, end_time puis le reste
cols = test_df.columns.tolist()
first_cols = ['patient_id', 'recording_id', 'date', 'start_time', 'end_time']
cols = first_cols + [col for col in cols if col not in first_cols]

Processing patient 2
Processing patient 0
Processing patient 1
Processing patient 3
Processing patient 4
Processing patient 5
Processing patient 7
Processing patient 11
Processing patient 12
Processing patient 8
Processing patient 6
Processing patient 10
Processing patient 9
Processing patient 13

In [10]:
test_df.head()

,patient_id,date,start_time,end_time,audspec_lengthL1norm_sma_iqr1_2,audspec_lengthL1norm_sma_iqr2_3,audspec_lengthL1norm_sma_iqr1_3,audspec_lengthL1norm_sma_percentile50_0,audspec_lengthL1norm_sma_stddev,audspec_lengthL1norm_sma_amean,...,logHNR_sma_de_iqr1_3,logHNR_sma_de_percentile50_0,logHNR_sma_de_stddev,F0final_sma_ff0_nnz,patient_short_id,label,age,sex,audio_quality,recording_id
0,2,2021-10-01,480,680,0.824093,0.237206,1.061300,1.294769,0.601383,1.036854,...,0.204519,0.065431,0.157982,1.000000,patient_0002,0,0.909091,0,0.557534,0
1,2,2021-10-01,480,680,0.825607,0.208997,1.034604,1.211626,0.564895,0.933170,...,0.190211,0.089150,0.180251,1.000000,patient_0002,0,0.909091,0,0.557534,1
2,2,2021-10-01,480,680,0.655419,0.376667,1.032087,1.198619,0.577098,1.036244,...,5.338002,0.086555,3.712759,0.846154,patient_0002,0,0.909091,0,0.557534,2
3,2,2021-10-01,480,680,0.679861,0.330526,1.010386,1.171579,0.563352,0.997027,...,0.251099,0.082160,0.181627,1.000000,patient_0002,0,0.909091,0,0.557534,3
4,2,2021-10-01,576,776,0.635661,0.266532,0.902193,1.221095,0.526917,1.019168,...,5.419852,0.062196,3.722184,0.846154,patient_0002,0,0.909091,0,0.809958,4

In [11]:
import numpy as np
pca_df = test_df.copy()

pca_df = pca_df.drop(columns=['patient_id','patient_short_id','date','start_time','end_time','label','recording_id'])

from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA


n = 2


scaler = StandardScaler()
pca_df = scaler.fit_transform(pca_df)

pca = PCA(n_components=n)
X_pca = pca.fit_transform(pca_df)


variance_taux = np.cumsum(pca.explained_variance_ratio_)[-1]

while variance_taux > 0.9 : 
    n+=1
    pca = PCA(n_components=n)
    X_pca = pca.fit_transform(pca_df)


    variance_taux = np.cumsum(pca.explained_variance_ratio_)[-1]

    print(n,' ',variance_taux)

In [12]:
dataset = []

for patient in test_df['patient_id'].unique():
    print (f"Processing patient {patient}")
    patient_data = test_df[test_df['patient_id'] == patient]
    for date in patient_data['date'].unique():
        date_data = patient_data[patient_data['date'] == date]
        
        for recording_id in date_data['recording_id'].unique():
            rec_data = date_data[date_data['recording_id'] == recording_id]
            element = {}
            element['patient_id'] = patient
            element['date'] = date
            #trier rec_data par start_time croissant
            rec_data = rec_data.sort_values(by='start_time')
            embeddings = []
            start_times = []
            end_times = []
            labels = []
            for i, row in rec_data.iterrows():
                #récuperer toutes les colonnes sauf patient_id, date, recording_id, start_time, end_time et les valeurs non numériques sous forme de liste
                embedding = row.drop(labels=['patient_id','patient_short_id','label', 'date', 'recording_id', 'start_time', 'end_time']).tolist()
                #print(f'Patient {patient}, embedding length: {len(embedding)}')
                embeddings.append(embedding)
                start_times.append(row['start_time'])
                end_times.append(row['end_time'])
                labels.append(row['label'])
            
            element['embeddings'] = embeddings
            element['start_times'] = start_times
            element['end_times'] = end_times
            element['label'] = labels[0]

            dataset.append(element)

Processing patient 2
Processing patient 0
Processing patient 1
Processing patient 3
Processing patient 4
Processing patient 5
Processing patient 7
Processing patient 11
Processing patient 12
Processing patient 8
Processing patient 6
Processing patient 10
Processing patient 9
Processing patient 13

In [13]:
len(dataset[0]['embeddings'])

43

In [14]:
import numpy as np
from datetime import datetime

positive_pairs = []
negative_pairs = []

i = 0
for data1 in dataset:

    if i % 100 == 0:
        print(f"Processing record {i} / {len(dataset)}")
    
    i += 1
    patient_id = data1['patient_id']
    date = data1['date']
    embeddings = data1['embeddings']

    #récupérer toutes les autres dates pour le même patient
    other_dates = [d['date'] for d in dataset if d['patient_id'] == patient_id and d['date'] != date]

    #récupérer si elles existent les dates les plus proches avant et après
    date_obj = datetime.strptime(date, '%Y-%m-%d')
    before_dates = [d for d in other_dates if datetime.strptime(d, '%Y-%m-%d') < date_obj]
    after_dates = [d for d in other_dates if datetime.strptime(d, '%Y-%m-%d') > date_obj]
    closest_before = max(before_dates, key=lambda d: datetime.strptime(d, '%Y-%m-%d')) if before_dates else None
    closest_after = min(after_dates, key=lambda d: datetime.strptime(d, '%Y-%m-%d')) if after_dates else None

    for data2 in dataset :
        if data2['patient_id'] == patient_id and data2['date'] in [closest_before, date_obj, closest_after]:
            positive_pairs.append([embeddings, data2['embeddings']])
            
        else :
            negative_pairs.append([embeddings, data2['embeddings']])

pairs = []

for pos in positive_pairs:
    pairs.append([pos[0], pos[1], 1])  # 1 for positive pair

for neg in negative_pairs:
    pairs.append([neg[0], neg[1], 0])  # 0 for negative pair

Processing record 0 / 1975
Processing record 100 / 1975
Processing record 200 / 1975
Processing record 300 / 1975
Processing record 400 / 1975
Processing record 500 / 1975
Processing record 600 / 1975
Processing record 700 / 1975
Processing record 800 / 1975
Processing record 900 / 1975
Processing record 1000 / 1975
Processing record 1100 / 1975
Processing record 1200 / 1975
Processing record 1300 / 1975
Processing record 1400 / 1975
Processing record 1500 / 1975
Processing record 1600 / 1975
Processing record 1700 / 1975
Processing record 1800 / 1975
Processing record 1900 / 1975

In [15]:
import base64
import gzip
from contextlib import contextmanager
from dataclasses import dataclass
from typing import Dict, Iterable, Optional, Tuple

import numpy as np
import torch
import torch.nn.functional as F
from torch import Tensor, nn

In [16]:
class PositionEncoding(nn.Module):
    def __init__(self, d_model=784, max_len=100):
        super().__init__()
        pe = torch.zeros(max_len, d_model)
        position = torch.arange(0, max_len, dtype=torch.float32).unsqueeze(1)
        embedding_index = torch.arange(0, d_model, 2, dtype=torch.float32)
        div_term = 1 / torch.tensor(10000.0) ** (embedding_index / d_model)
        pe[:, 0::2] = torch.sin(position * div_term)
        pe[:, 1::2] = torch.cos(position * div_term)
        self.register_buffer('pe', pe)  # (max_len, d_model)

    def forward(self, word_embeddings):
        # accepts (batch, seq_len, d_model) or (seq_len, d_model)
        if word_embeddings.dim() == 3:
            seq_len = word_embeddings.size(1)
            pe = self.pe[:seq_len].unsqueeze(0).to(word_embeddings.device).to(word_embeddings.dtype)  # (1, seq_len, d_model)
            return word_embeddings + pe
        else:
            seq_len = word_embeddings.size(0)
            pe = self.pe[:seq_len].to(word_embeddings.device).to(word_embeddings.dtype)  # (seq_len, d_model)
            return word_embeddings + pe


    
class SelfMultiheadAttention(nn.Module):
    def __init__(self, d_emb=784, nhead=8,d_out=None):
        super().__init__()
        assert d_emb % nhead == 0, "d_emb must be divisible by nhead"
        
        self.d_model = d_emb // nhead
        self.nhead = nhead
        self.PositionalEncoding = PositionEncoding(d_model=d_emb,max_len=100)
        self.Q = nn.Linear(d_emb, d_emb) # d_emb x d_emb
        self.K = nn.Linear(d_emb, d_emb) # d_emb x d_emb
        self.V = nn.Linear(d_emb, d_emb) # d_emb x d_emb

        if d_out is None:
            d_out = d_emb

        self.out = nn.Linear(d_emb, d_out) # d_emb x d_out
    
    def forward(self, x, mask=None):

        batch_size, seq_len, d_emb = x.size()

        Q = self.Q(x).view(batch_size, seq_len, self.nhead, self.d_model).transpose(1, 2)  # batch_size x nhead x seq_len x d_model
        K = self.K(x).view(batch_size, seq_len, self.nhead, self.d_model).transpose(1, 2)  # batch_size x nhead x seq_len x d_model
        V = self.V(x).view(batch_size, seq_len, self.nhead, self.d_model).transpose(1, 2)  # batch_size x nhead x seq_len x d_model

        scores = torch.matmul(Q, K.transpose(-2, -1)) / np.sqrt(self.d_model) 
        if mask is not None:
            scores = scores.masked_fill(mask == 0, float('-inf'))
        attn_weights = F.softmax(scores, dim=-1)

        attn_output = torch.matmul(attn_weights, V)
        attn_output = attn_output.transpose(1, 2).contiguous().view(batch_size, seq_len, d_emb)

        logits = self.out(attn_output)

        return logits
    

class TransformerEncoderLayer(nn.Module):
    def __init__(self, d_model=784, nhead=8, dropout=0.1):
        super().__init__()
        dim_feedforward = d_model * 4
        self.self_attn = SelfMultiheadAttention(d_model, nhead, d_out=d_model)
        self.linear1 = nn.Linear(d_model, dim_feedforward)
        self.dropout = nn.Dropout(dropout)
        self.linear2 = nn.Linear(dim_feedforward, d_model)

        self.norm1 = nn.LayerNorm(d_model)
        self.norm2 = nn.LayerNorm(d_model)
        self.dropout1 = nn.Dropout(dropout)
        self.dropout2 = nn.Dropout(dropout)

        self.activation = F.relu

    def forward(self, src,mask=None):
        src2 = self.self_attn(src,mask=mask)
        src = src + self.dropout1(src2)
        src = self.norm1(src)
        src2 = self.linear2(self.dropout(self.activation(self.linear1(src))))
        src = src + self.dropout2(src2)
        src = self.norm2(src)
        return src

class SelfMultiheadAttentionPoolingProjector(nn.Module):
    def __init__(self, d_emb=784, nhead=8):
        super().__init__()
        assert d_emb % nhead == 0, "d_emb must be divisible by nhead"
        
        self.d_model = d_emb // nhead
        self.nhead = nhead
        self.Attention = SelfMultiheadAttention(d_emb=d_emb, nhead=nhead, d_out=1)

    def forward(self, x, mask=None, temp=1.0):

        logits = self.Attention(x, mask=mask)

        weights = F.softmax(logits.squeeze()/temp)

        # weighted sum of the input embeddings
        logits = torch.sum(x * weights.unsqueeze(-1), dim=1)


        return logits,weights
    
class Embedder(nn.Module):
    def __init__(self, d_emb=784, nhead=8, num_transformer_layers=2,num_mlp_layers=2, d_projector=None):
        super().__init__()
        if d_projector is None:
            d_projector = d_emb
            
        self.d_projector = d_projector
        self.d_model = d_projector // nhead

        self.nhead = nhead
        self.num_transformer_layers = num_transformer_layers
        self.num_mlp_layers = num_mlp_layers

        self.InitialProjector = nn.Linear(d_emb, d_projector)
        self.PositionalEncoding = PositionEncoding(d_model=d_projector,max_len=1000)
        self.TransformerLayers = nn.ModuleList([
            TransformerEncoderLayer(d_model=d_projector, nhead=nhead) for _ in range(num_transformer_layers)
        ])

        self.AttentionPooling = SelfMultiheadAttentionPoolingProjector(d_emb=d_projector, nhead=nhead)

        self.MLP_layers = nn.ModuleList(
            nn.Sequential(
                nn.Linear(d_projector, d_projector),
                nn.ReLU(),
                nn.Linear(d_projector, d_projector)
            ) for _ in range(num_mlp_layers)
        )

    def forward(self, x, mask=None):

        x = self.InitialProjector(x)
        
        x = self.PositionalEncoding(x)

        for layer in self.TransformerLayers:
            x = layer(x, mask=mask)

        x, weights = self.AttentionPooling(x, mask=mask)

        for mlp in self.MLP_layers:
            x = mlp(x)

        return x
    

    def __repr__(self):
        #take the number of parameters in the model
        n_params = sum(p.numel() for p in self.parameters() if p.requires_grad)
        return f"Embedder(d_emb={self.d_model * self.nhead}, nhead={self.nhead}, num_transformer_layers={len(self.TransformerLayers)}, num_mlp_layers={len(self.MLP_layers)}, n_params={n_params})"

In [17]:
embedder = Embedder(d_emb=784,
                     nhead=8,
                     num_transformer_layers=1,
                     num_mlp_layers=1,
                     d_projector=64)

embedder

Embedder(d_emb=64, nhead=8, num_transformer_layers=1, num_mlp_layers=1, n_params=121089)

In [18]:
emb=dataset[0]['embeddings']
print(torch.tensor(emb).shape)
l= embedder(torch.tensor(emb).unsqueeze(0).float())
print(l.shape)

torch.Size([43, 784])
torch.Size([1, 64])

C:\Users\castr\AppData\Local\Temp\ipykernel_2416\4228471505.py:101: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  weights = F.softmax(logits.squeeze()/temp)

# Entraînement

In [19]:
pairs = [(a,b,1) for (a,b) in positive_pairs] + [(a,b,0) for (a,b) in negative_pairs]

In [20]:
from torch.utils.data import DataLoader, Dataset

In [21]:
class EmbeddingDataset(Dataset):
    """
    Dataset contenant des paires (z1, z2) et un label.
    Chaque z est une liste de vecteurs (seq_len, emb_dim)
    """
    def __init__(self, data):
        """
        data : list of tuples (z1, z2, label)
               z1 and z2 : list of embeddings [seq_len, emb_dim]
               label : scalar
        """
        self.data = data

    def __len__(self):
        return len(self.data)

    def __getitem__(self, idx):
        return self.data[idx]

In [22]:
def embedding_collate_fn(batch):
    """
    Transforme une liste de samples en batch avec padding et masques.
    Renvoie le mask prêt pour SelfMultiheadAttention.
    """
    z_1_list = [torch.tensor(x[0], dtype=torch.float) for x in batch]
    z_2_list = [torch.tensor(x[1], dtype=torch.float) for x in batch]
    labels = torch.tensor([x[2] for x in batch], dtype=torch.float)

    # longueur max par batch
    max_len_z1 = max([z.shape[0] for z in z_1_list])
    max_len_z2 = max([z.shape[0] for z in z_2_list])
    emb_dim = z_1_list[0].shape[1]  # dimension embedding

    # batch padded
    z1_padded = torch.zeros((len(batch), max_len_z1, emb_dim))
    z2_padded = torch.zeros((len(batch), max_len_z2, emb_dim))
    
    # attention mask pour le batch
    attention_mask_z1 = torch.zeros((len(batch), 1, 1, max_len_z1), dtype=torch.bool)
    attention_mask_z2 = torch.zeros((len(batch), 1, 1, max_len_z2), dtype=torch.bool)

    for idx, z in enumerate(z_1_list):
        seq_len = z.shape[0]
        z1_padded[idx, :seq_len, :] = z
        attention_mask_z1[idx, :, :, :seq_len] = 1  # shape: (B,1,1,L)

    for idx, z in enumerate(z_2_list):
        seq_len = z.shape[0]
        z2_padded[idx, :seq_len, :] = z
        attention_mask_z2[idx, :, :, :seq_len] = 1

    return {
        "z_1": z1_padded,
        "attention_mask_z1": attention_mask_z1,
        "z_2": z2_padded,
        "attention_mask_z2": attention_mask_z2,
        "labels": labels
    }



def get_embedding_dataloader(dataset_list, batch_size=8, shuffle=True):
    """
    Crée un DataLoader PyTorch pour les embeddings
    """
    dataset = EmbeddingDataset(dataset_list)
    dataloader = DataLoader(
        dataset,
        batch_size=batch_size,
        shuffle=shuffle,
        collate_fn=embedding_collate_fn
    )
    return dataloader

In [23]:
dummy_input = torch.randn(4, 10, 784)  # Exemple : batch_size=4, seq_len=10, embedding_dim=784
output = embedder(dummy_input)
print("Output shape:", output.shape)

Output shape: torch.Size([4, 64])

C:\Users\castr\AppData\Local\Temp\ipykernel_2416\4228471505.py:101: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  weights = F.softmax(logits.squeeze()/temp)

In [24]:
dataloader = get_embedding_dataloader(pairs, batch_size=4)

In [25]:
import torch.nn.functional as F

def contrastive_loss(emb1, emb2, labels, temperature=0.5):
    """
    emb1, emb2: (batch_size, d_emb)
    labels: 1 si similaire, 0 sinon
    """
    # Normalisation
    emb1 = F.normalize(emb1, dim=1)
    emb2 = F.normalize(emb2, dim=1)

    # Similarité cosine
    sim = torch.sum(emb1 * emb2, dim=1) / temperature  # (batch_size,)

    # Labels 1 -> positive, 0 -> negative
    loss = F.binary_cross_entropy_with_logits(sim, labels)
    return loss

In [26]:
# Device
device = torch.device("cpu")

# Embedder
embedder = Embedder(d_emb=784,
                     nhead=8,
                     num_transformer_layers=0,
                     num_mlp_layers=0,
                     d_projector=64).to(device)

# Optimizer
optimizer = torch.optim.Adam(embedder.parameters(), lr=1e-4)

In [27]:
embedder

Embedder(d_emb=64, nhead=8, num_transformer_layers=0, num_mlp_layers=0, n_params=62785)

In [28]:
# Loop d'entraînement
for epoch in range(1):  # petit test
    embedder.train()
    total_loss = 0
    i = 0
    for batch in dataloader:
        if i % 100 == 0:
            print(f"Processing batch {i+1}/{len(dataloader)}")
        i += 1
        Z1 = batch["z_1"].to(device)
        Z2 = batch["z_2"].to(device)
        mask1 = batch["attention_mask_z1"].to(device)
        mask2 = batch["attention_mask_z2"].to(device)
        labels = batch["labels"].to(device)

        optimizer.zero_grad()
        emb1 = embedder(Z1, mask=mask1)
        emb2 = embedder(Z2, mask=mask2)

        loss = contrastive_loss(emb1, emb2, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item()
    
    print(f"Epoch {epoch+1}, Loss: {total_loss/len(dataloader):.4f}")

Processing batch 1/975157

C:\Users\castr\AppData\Local\Temp\ipykernel_2416\4228471505.py:101: UserWarning: Implicit dimension choice for softmax has been deprecated. Change the call to include dim=X as an argument.
  weights = F.softmax(logits.squeeze()/temp)

Processing batch 101/975157
Processing batch 201/975157
Processing batch 301/975157
Processing batch 401/975157
Processing batch 501/975157
Processing batch 601/975157
Processing batch 701/975157
Processing batch 801/975157
Processing batch 901/975157
Processing batch 1001/975157
Processing batch 1101/975157
Processing batch 1201/975157
Processing batch 1301/975157
Processing batch 1401/975157
Processing batch 1501/975157
Processing batch 1601/975157
Processing batch 1701/975157
Processing batch 1801/975157
Processing batch 1901/975157

KeyboardInterrupt:

In [ ]:
#exporter les poids du modèle
torch.save(embedder.state_dict(), "embedder_weights.pth")